# -- Main Menu --

[[main]]
  name = "关于我们"
  pageRef = "about"
  weight = 10

[[main]]
  name = "音乐"
  pageRef = "music"
  weight = 20


[[main]]
  name = "动态"
  pageRef = "news"
  weight = 40

# -- Footer Menu --
[[footer]]
  name = "关于我们"
  pageRef = "about"
  weight = 10
