# -- Main Menu --
# The template is configured to show pages with a menuWeight set
# to their title. This defines the page order in the menu.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Music"
  pageRef = "music"
  weight = 20

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 30

[[main]]
  name = "News"
  pageRef = "news"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

# -- Footer Menu --
[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 20
