# -- Theme Options --
# The Boovan Band - Theme Configuration
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "boovan"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = false

mainSections = ["news", "music"]

disableImageOptimization = false
defaultBackgroundImage = "/images/band2025.jpg"
defaultFeaturedImage = "/images/band2025.jpg"

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/news"
  cardView = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = true
  sharingLinks = ["facebook", "twitter", "email"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  cardView = true
  groupByYear = false
